[package]
name = "yasc"
version = "0.1.0"
authors = ["Evgeny Barbashov <evgeny.barbashov@gmail.com>"]
license = "MIT"

[dependencies]
hex2d = { git = "https://github.com/dpc/hex2d-rs", rev = "e3d6d85"}
